service: nestjs-api-lambda-app

plugins:
 - serverless-offline

provider:
 name: aws
 runtime: nodejs18.x

functions:
 main:
   handler: dist/lambda.handler
   events:
     - http:
         method: any
         path: /{any+}